[package]
name = "blockgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam="0.24.2"
softbuffer = "0.3.1"
winit="0.28.7"
wgpu="0.17.1"
pollster="0.3.0"
env_logger="0.10.0"
