[package]
name = "lua2js"
version = "0.1.0"
edition = "2021"

[dependencies]
full_moon = { version = "0.18.1", features = ["roblox"], default-features = false }  # parse lua
seesea = { path = "../../seesea", default-features = false }  # parse c https://github.com/LukeGrahamLandry/seesea
